IdentityMySQLDemo/Controllers/UserController.cs
using AspNet.Identity.MySQL;
using Focus.BL.Common.Services;
using IdentityMySQLDemo.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using Focus.DAL.Common.DbModels;
using System.Threading.Tasks;
using System.Web.Mvc;
using Focus.Web.Models;
using Focus.Web.Helpers;
using AutoMapper;
using System.Web;
using Microsoft.AspNet.Identity.Owin;
using Messages = IdentityMySQLDemo.Properties.Resources;

namespace IdentityMySQLDemo.Controllers
{
    [Authorize(Roles = "admin, auditor")]
    public class UserController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext("OracleDbContext");
        private ApplicationSignInManager _signInManager;
        UserManager<ApplicationUser> userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext("OracleDbContext")));
        RoleManager<IdentityRole> RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext("OracleDbContext")));

        private readonly IInspectorService _inspectorService;
        private readonly IPostService _postService;
        private readonly IRoleService _roleService;
        private readonly IUserRoleService _userRoleService;

        public UserController(IInspectorService inspectorService, IPostService postService, IRoleService roleService, IUserRoleService userRoleService)
        {
            _inspectorService = inspectorService;
            _postService = postService;
            _roleService = roleService;
            _userRoleService = userRoleService;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ActionResult DateUpdate()
        {
            List<ApplicationUser> usersList = userManager.Users.ToList();
            const int SECONDS_BEHIND_COUNT = 5;
            DateTime nowUtc = DateTime.UtcNow.AddSeconds(-SECONDS_BEHIND_COUNT);
            foreach (var user in usersList)
            {
                user.LockoutEndDateUtc = nowUtc;
                userManager.Update(user);
            }

            return View("Index", usersList);
        }

        // GET: User
        public ActionResult Index()
        {

            var users = new List<UsersViewModel>();
            UsersViewModel user = null;
            List<ApplicationUser> usersList = userManager.Users.OrderBy(u => u.UserName).ToList();
            List<POST> posts = _postService.GetAllPosts().ToList();
            List<INSPECTOR> inspectors = _inspectorService.GetAllInspectors().ToList();
            List<ROLES> roles = _roleService.GetAllRoles().ToList();
            List<USERROLES> userRoles = _userRoleService.GetAllUserRoles().ToList();
            foreach (ApplicationUser item in usersList)
            {
                string roleId = userRoles.Where(ur => ur.USERID == item.Id).FirstOrDefault()?.ROLEID;
                string role = roles.Where(r => r.ID == roleId).FirstOrDefault()?.NAME;
                //bool idAdmin = userManager.IsInRole(item.Id, "admin");
                DateTime? lockoutEndDate = item.LockoutEndDateUtc;
                short inspectorId = (short)item.PERSONID;
                INSPECTOR inspector = inspectors.Where(i => i.ID == inspectorId).FirstOrDefault();
                if (inspector != null)
                {
                    string title = inspector.TITLE;
                    string shortName = inspector.SHORTNAME;
                    string phoneNumber = inspector.PHONENUMBER;
                    byte postId = inspector.POSTID ?? 0;
                    POST post = posts.Where(p => p.ID == postId).FirstOrDefault();
                    if (post != null)
                    {
                        string code = post.CODE;
                        string namePto = post.NAME;
                        string division = post.DEVISION;
                        user = new UsersViewModel() { Id = item.Id, UserName = item.UserName, Role = role, ShortName = shortName, CodePTO = code, PTOName = namePto, Division = division, Title = title, PhoneNumber = phoneNumber, LockoutEndDate = lockoutEndDate };
                        users.Add(user);
                        continue;
                    }
                    user = new UsersViewModel() { Id = item.Id, UserName = item.UserName, Role = role, ShortName = shortName, Title = title, PhoneNumber = phoneNumber, LockoutEndDate = lockoutEndDate };
                    users.Add(user);
                    continue;
                }

                user = new UsersViewModel() { Id = item.Id, UserName = item.UserName, Role = role, LockoutEndDate = lockoutEndDate };
                users.Add(user);
            }
            return View(users);
        }

        // GET: User/Edit/5
        public async Task<ActionResult> ChangePassword(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = await userManager.FindByIdAsync(id);
            var userId = applicationUser.Id;
            var role = userManager.GetRoles(userId).FirstOrDefault();
            var user = new RegisterViewModel() { UserName = applicationUser.UserName, Role = role };
            if (applicationUser == null)
            {
                return HttpNotFound();
            }

            return View(user);
        }

        // POST request.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(RegisterViewModel usermodel)
        {
            var user = await userManager.FindByNameAsync(usermodel.UserName);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user.PasswordHash = userManager.PasswordHasher.HashPassword(usermodel.Password);
            var result = await userManager.UpdateAsync(user);
            if (!result.Succeeded)
            {
                return View(usermodel);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult doesUserNameExist(string UserName)
        {

            var user = userManager.FindByName(UserName);
            if (user == null)
                return Json(true, JsonRequestBehavior.AllowGet);

            string suggestedUID = String.Format(CultureInfo.InvariantCulture,
                "user с имененем '{0}' уже существует. Пожалуйста, введите другое имя пользователя.", UserName);
            return Json(suggestedUID, JsonRequestBehavior.AllowGet);
        }

        // Remote diagnostics.
        // GET: Inspector /NotRepeated/
        [AllowAnonymous]
        public JsonResult NotRepeated(string FIRSTNAME, string LASTNAME, string FATHERNAME)
        {
            if (IsEnique(FIRSTNAME, LASTNAME, FATHERNAME))
            {
                return Json(true,
                    JsonRequestBehavior.AllowGet);
            }

            return Json(
                    string.Format(
                        Messages.ErrorRemoteInspectorRepeated,
                        LASTNAME ?? string.Empty,
                        FIRSTNAME ?? string.Empty,
                        FATHERNAME ?? string.Empty),
                        JsonRequestBehavior.AllowGet);
        }

        private bool IsEnique(string firstName, string lastName, string fatherName)
        {
            return !_inspectorService.InspectorExists(
                    i => i.FIRSTNAME == (firstName == string.Empty ? null : firstName) &&
                    i.LASTNAME == (lastName == string.Empty ? null : lastName) &&
                    i.FATHERNAME == (fatherName == string.Empty ? null : fatherName));
        }

        public ActionResult LockAccount(string id)
        {
            ApplicationUser user = userManager.FindById(id);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            const int LOCKOUT_MINUTES_COUNT = 15;
            LockAccount(user.UserName, LOCKOUT_MINUTES_COUNT);

            return RedirectToAction("Index");
        }

       
        public ActionResult LockoutAccount(string Id)
        {
            ApplicationUser user = userManager.FindById(Id);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            const int SECONDS_BACKWARD = 5;
            LockoutAccount(user.UserName, -SECONDS_BACKWARD);

            return RedirectToAction("Index");
        }

        private void LockoutAccount(string userName, int seconds = 0)
        {
            var user = userManager.FindByName(userName);

            DateTime lockoutEndDate = DateTime.Now.ToUniversalTime();
            if (seconds == 0)
            {
                userManager.SetLockoutEndDate(user.Id, lockoutEndDate);
            }
            else
            {
                lockoutEndDate = DateTime.Now.AddSeconds(seconds);
                userManager.SetLockoutEndDate(user.Id, lockoutEndDate);
            }
        }

        private void LockAccount(string userName, int minutes = 0)
        {
            ApplicationUser user = userManager.FindByName(userName);

            DateTime lockoutEndDate = DateTime.Now.ToUniversalTime();
            if (minutes == 0)
            {
                const int LOCKOUT_YEARS_COUNT = 100;
                lockoutEndDate = lockoutEndDate.AddYears(LOCKOUT_YEARS_COUNT);
                userManager.SetLockoutEndDate(user.Id, lockoutEndDate);
            }
            else
            {

IdentityMySQLDemo/Views/User/ChangePassword.cshtml
@model IdentityMySQLDemo.Models.RegisterViewModel
@{
    ViewBag.Title = "Изменение пароля пользователя";
}

<div class="container body-content">
    <h2>@ViewBag.Title</h2>

    @using (Html.BeginForm("ChangePassword", "User", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @*<h4>Create a new account.</h4>*@
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserName)
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Role)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Role)
            </dd>
        </dl>
        <div class="form-group">
            @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Изменить пароль" />
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Вернуться к списку", "Index")
    </div>
</div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

IdentityMySQLDemo/Views/User/Create.cshtml
@model IdentityMySQLDemo.Models.RegisterViewModel
@{

    ViewBag.Message2 = "Создание нового пользователя";
}

<div class="container body-content">
    <div class="container body-content">
        <h2>@ViewBag.Message2</h2>

        @using (Html.BeginForm("Create", "User", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <hr />
            @Html.ValidationSummary("", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ROLE", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Инспектор</div>
                <ul class="list-group">
                    <li class="list-group-item">
                        <div class="form-group">
                            @Html.LabelFor(model => model.PERSONID, "", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="input-group" style="max-width: 272px;">
                                    <label for="hiddenFieldConsigneeId">Введите инспектора...</label>
                                    @Html.HiddenFor(model => model.PERSONID, new { htmlAttributes = new { @class = "form-control", @placeholde = "Выберите инспектора ...", @hidden = "hidden" } })
                                    <span class="input-group-btn">
                                        <button id="buttonConsigneeId" class="btn btn-default" type="button" onclick="ShowInspectorModal()">Выбрать</button>
                                    </span>
                                </div>
                                @Html.ValidationMessageFor(model => model.PERSONID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Фамилия", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("LASTNAME", null, new { htmlAttributes = new { @class = "form-control", id = "LASTNAME", @disabled = "disabled" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Имя", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("FIRSTNAME", null, new { htmlAttributes = new { @class = "form-control", id = "FIRSTNAME", @disabled = "disabled" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Отчество", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("FATHERNAME", null, new { htmlAttributes = new { @class = "form-control", id = "FATHERNAME", @disabled = "disabled" } })
                            </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="form-group">
                            @Html.Label("Должность", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("TITLE", null, new { htmlAttributes = new { @class = "form-control", id = "TITLE", @disabled = "disabled" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Телефон", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("PHONENUMBER", null, new { htmlAttributes = new { @class = "form-control", id = "PHONENUMBER", @disabled = "disabled" } })
                            </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="form-group">
                            @Html.Label("Код ПТО", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("CODE", null, new { htmlAttributes = new { @class = "form-control", id = "CODE", @disabled = "disabled" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("ПТО", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("NAME", null, new { htmlAttributes = new { @class = "form-control", id = "NAME", @disabled = "disabled" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Отдел/таможенный пост", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("DEVISION", null, new { htmlAttributes = new { @class = "form-control", id = "DEVISION", @disabled = "disabled" } })
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-default" value="Создать" />
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Вернуться к списку", "Index")
        </div>
    </div>
        <!--Open inspector modal by javascript-->
        <script type="text/javascript">
            function ShowInspectorModal() {
                $('#inspresults').empty();
                $("#inspModal").modal();

            }
        </script>

        <!-- Insp Modal -->
        <script type="text/javascript">
            function OnSuccessInspector(data) {
                var devision = $('#DEVISION');
                devision.val(data.devision);
                var id = $('#PERSONID');
                id.val(data.id);
                var lastname = $('#LASTNAME');
                lastname.val(data.lastname);
                var firstname = $('#FIRSTNAME');
                firstname.val(data.firstname);
                var fathername = $('#FATHERNAME');
                fathername.val(data.fathername);
                var postname = $('#NAME');
                postname.val(data.postname);
                var code = $('#CODE');
                code.val(data.code);
                var phonenumber = $('#PHONENUMBER');
                phonenumber.val(data.phonenumber);
                var title = $('#TITLE');
                title.val(data.title);
                $('#inspModal').modal('hide');
            }</script>

        <div class="modal fade" id="inspModal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Выбор инспектора</h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            @using (Ajax.BeginForm("Search", "Inspector", new AjaxOptions { UpdateTargetId = "inspresults", OnSuccess = "InspectorButtonCloseShow" }))
                            {
                                <div class="input-group" style="max-width: 380px;">
                                    <input type="text" class="form-control" name="name" placeholder="Введите часть фамилии ..." />
                                    <div class="input-group-btn">
                                        <button type="submit" onclick="$('#inspresults').empty()" class="btn btn-default">Поиск</button>
                                        @Ajax.ActionLink("Создать", "PartialCreate", "Inspector", null,
                                     new AjaxOptions { UpdateTargetId = "inspresults", OnSuccess= "InspectorButtonCloseHide" }, new { @class = "btn btn-default" } )
                                    </div>
                                </div>

                            }
                            <div id="inspresults"></div>
                        </div>
                    </div>
                    <div class="modal-footer" id="InspectorFooter">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function InspectorButtonCloseHide() {
            $('#InspectorFooter').hide();

        }
    </script>
    <script>
        function InspectorButtonCloseShow() {
            $('#InspectorFooter').show();

        }
    </script>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

IdentityMySQLDemo/Views/User/CreateAdministrator.cshtml
@model IdentityMySQLDemo.Models.RegisterAdministratorViewModel
@{

    ViewBag.Message2 = "Создание администратора системы";
}

<div class="container body-content">
    <div class="container body-content">
        <h2>@ViewBag.Message2</h2>

        @using (Html.BeginForm("CreateAdministrator", "User", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <hr />
            @Html.ValidationSummary("", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", @Value = "administrator"})
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Инспектор</div>
                <ul class="list-group">
                    <li class="list-group-item">

                        <div class="form-group">
                            @Html.Label("Фамилия", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("LASTNAME", null, new { htmlAttributes = new { @class = "form-control", id = "LASTNAME" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Имя", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("FIRSTNAME", null, new { htmlAttributes = new { @class = "form-control", id = "FIRSTNAME" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Отчество", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("FATHERNAME", null, new { htmlAttributes = new { @class = "form-control", id = "FATHERNAME" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Фамилия, инициалы", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("SHORTNAME", null, new { htmlAttributes = new { @class = "form-control", id = "SHORTNAME" } })
                            </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="form-group">
                            @Html.Label("Должность", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("TITLE", null, new { htmlAttributes = new { @class = "form-control", id = "TITLE" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Телефон", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Editor("PHONENUMBER", null, new { htmlAttributes = new { @class = "form-control", id = "PHONENUMBER" } })
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-default" value="Создать" />
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Вернуться к списку", "Index")
        </div>
    </div>
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

IdentityMySQLDemo/Views/User/Delete.cshtml
@model IdentityMySQLDemo.Models.UserViewModel

@{
    ViewBag.Title = "Удаление пользователя";
}

<div class="container body-content">
    <div class="container body-content">
        <h2>Удаление пользователя</h2>

        <h3>Вы уверены, что хотите удалить указанного пользователя?</h3>
        <div>
            <hr />
            @Html.HiddenFor(model => model.Id)
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.UserName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Role)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Role)
                </dd>
            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-default" value="Удалить" />
                    </div>
                </div>
            }
        </div>
        <div>
            @Html.ActionLink("Вернуться к списку", "Index")
        </div>
    </div>
</div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

IdentityMySQLDemo/Views/User/Index.cshtml
@model IEnumerable< IdentityMySQLDemo.Models.UsersViewModel>

@{ DateTime? current = DateTime.Now.ToUniversalTime();}

@{
    ViewBag.Title = "Пользователи системы";
}
<div class="container container-fluid">
<h2>Пользователи системы</h2>

<p>
    @Html.ActionLink("Создание нового пользователя", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Role)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodePTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PTOName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Division)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Role)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShortName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CodePTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PTOName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Division)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.ActionLink("Изменить", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Сбросить пароль", "ChangePassword", new { id = item.Id }) |
            @Html.ActionLink("Удалить", "Delete", new { id = item.Id }) |
            @if (item.LockoutEndDate > current)
            {
                @Html.ActionLink("Разблокировать", "LockoutAccount", "User", new { id = item.Id }, new { @style = "color:red" })
            }
            else
            {
                @Html.ActionLink("Заблокировать", "LockAccount", "User", new { id = item.Id }, null)
            }
        </td>

    </tr>
}

</table>

</div>