Focus.SSO/Models/permission.cs
namespace Focus.SSO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permission()
        {
        }

            [Display(Name = "Код разрешения")]
            public short PERMISSIONID { get; set; }
            [Display(Name = "Код документа")]
            public Nullable<short> DOCUMENTID { get; set; }
            [Required(ErrorMessage = "Требуется ввести дату начала действия полномочий.")]
            [DataType(DataType.Date)]
            [Display(Name = "Дата начала")]
            public Nullable<System.DateTime> DATESTART { get; set; }
            [Required(ErrorMessage = "Требуется ввести дату завершения действия полномочий.")]
            [Display(Name = "Дата завершения")]
            [DataType(DataType.Date)]
            public Nullable<System.DateTime> DATEFINISH { get; set; }
            [Display(Name = "Разрешение действует")]
            public Nullable<byte> ISVALID { get; set; }
            [Display(Name = "Пользователь")]
            [MaxLength(256)]
            public string USERID { get; set; }
            [Display(Name = "Обновлен")]
            public System.DateTime LAST_UPDATE { get; set; }

        public virtual Document DOCUMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Custombrocker> CUSTOMBROCKER { get; set; }
    }
}

Focus.SSO/Controllers/permissionsController.cs
using AutoMapper;
using Focus.BL.Common.Services;
using Focus.DAL.Common.DbModels;
using Focus.SSO.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Focus.Controllers
{
    public class permissionsController : Controller
    {
        private IPermissionService _permissionService;
        private IDocumentService _documentService;
        private IDocumentkindService _documentkindService;
        private ICustombrockerService _custombrockerService;


        public permissionsController(IPermissionService permissionService,IDocumentService documentService, IDocumentkindService documentkindService, ICustombrockerService custombrockerService)
        {
            _permissionService = permissionService;
            _documentService = documentService;
            _documentkindService = documentkindService;
            _custombrockerService = custombrockerService;
        }

        // GET: permissions
        public ActionResult Index()
        {
            var permissions = _permissionService.GetAllPermissions().ToList();
            return View(Mapper.Map<IEnumerable<PERMISSION>, IEnumerable<Permission>>(permissions));
        }

        // GET: permissions/Details/5
        public ActionResult Details(short id)
        {
            PERMISSION permission = _permissionService.GetPermission(id);
            if (permission == null)
            {
                return HttpNotFound();
            }
            return View(Mapper.Map<Permission>(permission));
        }

        public JsonResult JsonPermission(PERMISSION permission, string fullName, string workOfPlace, string post, string passport, string address, string phone, string fax)
        {
    
            //if (ModelState.IsValid)
            //{
                var custombrockers = new List<CUSTOMBROCKER>();
                            foreach (var custombrocker in permission.CUSTOMBROCKER)
                            {
                                custombrockers.Add(_custombrockerService.GetCustombrocker(custombrocker.CUSTOMBROCKERID));
                            }

                            permission.CUSTOMBROCKER = null;

                try
                {
                    permission.LAST_UPDATE = DateTime.Now;
                    _permissionService.AddPermission(Mapper.Map<PERMISSION>(permission));

                    permission.CUSTOMBROCKER = custombrockers;

                    permission.LAST_UPDATE = DateTime.Now;
                    _permissionService.UpdatePermission(Mapper.Map<PERMISSION>(permission));

                    // Your code...
                    // Could also be before try if you know the exception occurs in SaveChanges
                    
                    //db.SaveChanges();
                }
                catch (DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {
                            Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                ve.PropertyName, ve.ErrorMessage);
                        }
                    }
                    throw;
                }

                var jsondata = _permissionService.GetPermission(permission.PERMISSIONID);
                return Json(
                    new
                    {
                        id = jsondata?.PERMISSIONID,
                        start = jsondata?.DATESTART == null ? "" : jsondata?.DATESTART.Value.ToShortDateString(),
                        finish = jsondata?.DATEFINISH == null ? "" : jsondata?.DATEFINISH.Value.ToShortDateString(),
                        valid = jsondata?.ISVALID == null ? false : Convert.ToBoolean(jsondata?.ISVALID.Value),
                        fullName,
                        workOfPlace,
                        post,
                        address,
                        passport,
                        phone,
                        fax
                    },
                    JsonRequestBehavior.AllowGet);
            //}
            //return Json(new { });
        }

           

        // GET: permissions/Create
        public ActionResult Create()
        {
            ViewBag.DOCUMENTID = new SelectList(Mapper.Map<IEnumerable<DOCUMENT>, IEnumerable<Document>>(_documentService.GetAllDocuments()), "DOCUMENTID", "NUMBER");
            ViewBag.DOCUMENTKINDID = new SelectList(Mapper.Map<IEnumerable<DOCUMENTKIND>, IEnumerable<Documentkind>>(_documentkindService.GetAllDocumentkinds()), "DOCUMENTKINDID", "NAME", 1);
            return View();
        }

        // GET: permissions/Create
        public ActionResult PartialCreate()
        {
            ViewBag.DOCUMENTID = new SelectList(Mapper.Map<IEnumerable<DOCUMENT>, IEnumerable<Document>>(_documentService.GetAllDocuments()), "DOCUMENTID", "NUMBER");
            return PartialView();
        }

        // POST: permissions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PERMISSIONID,DOCUMENTID,DATESTART,DATEFINISH,ISVALID,LAST_UPDATE")] Permission permission)
        {
            if (ModelState.IsValid)
            {
                permission.LAST_UPDATE = DateTime.Now;
                _permissionService.AddPermission(Mapper.Map<PERMISSION>(permission));
                return RedirectToAction("Index");
            }


            ViewBag.DOCUMENTKINDID = new SelectList(Mapper.Map<IEnumerable<DOCUMENTKIND>, IEnumerable<Documentkind>>(_documentkindService.GetAllDocumentkinds()), "DOCUMENTKINDID", "NAME", 1);
            ViewBag.DOCUMENTID = new SelectList(Mapper.Map<IEnumerable<DOCUMENT>, IEnumerable<Document>>(_documentService.GetAllDocuments()), "DOCUMENTID", "NUMBER", permission.DOCUMENTID);
            return View(permission);
        }

        // GET: permissions/Edit/5
        public ActionResult Edit(short id)
        {
            PERMISSION permission = _permissionService.GetPermission(id);
            if (permission == null)
            {
                return HttpNotFound();
            }
            ViewBag.DOCUMENTID = new SelectList(Mapper.Map<IEnumerable<DOCUMENT>, IEnumerable<Document>>(_documentService.GetAllDocuments()), "DOCUMENTID", "NUMBER", permission.DOCUMENTID);
            return View(Mapper.Map<Permission>(permission));
        }

        // POST: permissions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PERMISSIONID,DOCUMENTID,DATESTART,DATEFINISH,ISVALID,LAST_UPDATE")] Permission permission)
        {
            if (ModelState.IsValid)
            {
                permission.LAST_UPDATE = DateTime.Now;
                _permissionService.UpdatePermission(Mapper.Map<PERMISSION>(permission));
                return RedirectToAction("Index");
            }
            ViewBag.DOCUMENTID = new SelectList(Mapper.Map<IEnumerable<DOCUMENT>, IEnumerable<Document>>(_documentService.GetAllDocuments()), "DOCUMENTID", "NUMBER", permission.DOCUMENTID);
            return View(permission);
        }

        // GET: permissions/Delete/5
        public ActionResult Delete(short id)
        {
            PERMISSION permission = _permissionService.GetPermission(id);
            if (permission == null)
            {
                return HttpNotFound();
            }
            return View(Mapper.Map<Permission>(permission));
        }


        // GET: Permission/Delete/5
        public ActionResult PartialDelete(short id)
        {
            PERMISSION permission = _permissionService.GetPermission(id);
            if (permission == null)
            {
                return HttpNotFound();
            }
            return PartialView(Mapper.Map<Permission>(permission));
        }

        // POST: Permission/Delete/5
        [HttpPost, ActionName("PartialDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult PartialDeleteConfirmed(short id)
        {
            PERMISSION permission = _permissionService.GetPermission(id);
            _permissionService.DeletePermission(id);
            return PartialView("PermissionDeleted", Mapper.Map<Permission>(permission));
        }

        // POST: Permission/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PermissionDeleted(short id)
        {
            if (_permissionService.PermissionExists(p => p.PERMISSIONID == id))
            {
                _permissionService.DeletePermission(id);
            }
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
         

        // POST: permissions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(short id)
        {
            PERMISSION permission = _permissionService.GetPermission(id);
            _permissionService.DeletePermission(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _permissionService.Dispose();
                _documentService.Dispose();
                _documentkindService.Dispose();
            }

Focus.SSO/Views/permissions/Create.cshtml
@model Focus.SSO.Models.Permission

@{
    ViewBag.Title = "Создaть";
}

<h2>Создать</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>permission</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.DOCUMENTID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DOCUMENTID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DOCUMENTID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATESTART, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATESTART, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATESTART, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATEFINISH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATEFINISH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATEFINISH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ISVALID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ISVALID)
                    @Html.ValidationMessageFor(model => model.ISVALID, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Focus.SSO/Views/permissions/Delete.cshtml
@model Focus.SSO.Models.Permission

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Вы уверены, что хотите удалить?</h3>
<div>
    <h4>permission</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DATESTART)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATESTART)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATEFINISH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATEFINISH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ISVALID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ISVALID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LAST_UPDATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LAST_UPDATE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOCUMENT.NUMBER_)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOCUMENT.NUMBER_)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger" /> |
            @Html.ActionLink("Вернуться к списку", "Index")
        </div>
    }
</div>

Focus.SSO/Views/permissions/Details.cshtml
@model Focus.SSO.Models.Permission

@{
    ViewBag.Title = "Детали";
}

<h2>Детали</h2>

<div>
    <h4>permission</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DATESTART)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATESTART)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATEFINISH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATEFINISH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ISVALID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ISVALID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LAST_UPDATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LAST_UPDATE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOCUMENT.NUMBER_)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOCUMENT.NUMBER_)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.PERMISSIONID }) |
    @Html.ActionLink("Вернуться к списку", "Index")
</p>

Focus.SSO/Views/permissions/PermissionDeleted.cshtml
@model Focus.SSO.Models.Permission

<!--Body-->
<div class="modal-body">
    <div class="text-left">
        <i class="fa fa-check fa-4x mb-3 animated rotateIn"></i>
        <h5 class="text-danger">Указанное разрешение удалено</h5>
        <p>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.CUSTOMBROCKER.FirstOrDefault().LASTNAME)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CUSTOMBROCKER.FirstOrDefault().LASTNAME)
                <dd>
                <dt>
                    @Html.DisplayNameFor(model => model.CUSTOMBROCKER.FirstOrDefault().FIRSTNAME)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CUSTOMBROCKER.FirstOrDefault().FIRSTNAME)
                <dd>
                <dt>
                    @Html.DisplayNameFor(model => model.CUSTOMBROCKER.FirstOrDefault().FATHERSNAME)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CUSTOMBROCKER.FirstOrDefault().FATHERSNAME)
                <dd>
                <dt>
                    @Html.DisplayNameFor(model => model.CUSTOMBROCKER.FirstOrDefault().WORKPLACE)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CUSTOMBROCKER.FirstOrDefault().WORKPLACE)
                <dd>
                <dt>
                    @Html.DisplayNameFor(model => model.CUSTOMBROCKER.FirstOrDefault().POST)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CUSTOMBROCKER.FirstOrDefault().POST)
                <dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DATESTART)
                <dt>

                <dd>
                    @Html.DisplayFor(model => model.DATESTART)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DATEFINISH)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DATEFINISH)
                <dd>
            </dl>
    </div>
</div>
<!--Footer-->
<div class="modal-footer justify-content-center">

    @using (Ajax.BeginForm("PermissionDeleted", "permissions", new {id = @Model.PERMISSIONID}, new AjaxOptions() { }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="ОК" class="btn btn-primary" onclick="OnCustomBrockerPermissionDeleted(@Model.PERMISSIONID); $('#CustomBrockerPermissionDeleteModal').modal('hide');" />
        </div>
    }
</div>

Focus.SSO/Views/permissions/PermissionPartialCreate.cshtml
@model Focus.SSO.Models.Permission

    <!--Content-->
    @using (Ajax.BeginForm("JsonPermission", "permissions", new AjaxOptions { OnSuccess = "OnSuccessPermission" }))
    {

        <div class="modal-header">
            <button type="button" class="close" id="buttonPermissionModalClose" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Формирование разрешения</h4>
        </div>
        <div class="modal-body">
            <div class="panel panel-default">
                <div class="panel-heading">Период полномочий</div>
                <div class="panel-body">
                    <div class="form-horizontal">


                        <div class="form-group">
                            @Html.LabelFor(model => model.DATESTART, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DATESTART, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DATESTART, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DATEFINISH, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DATEFINISH, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DATEFINISH, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <hr />
            <div class="panel-group" id="permissionAccordion" role="tablist" aria-multiselectable="true">
                <div id="anchorForCustomBrockerpermission"></div>
            </div>
            <button type="button" class="btn btn-primary" id="buttonAddCustomBrocker" data-toggle="modal" data-target="#brockerModal">
                Добавить таможенного представителя
            </button>
            <div id="permissionresults"></div>
        </div>
        <div class="modal-footer" id="organizationFooter">
            <button type="submit" disabled class="btn btn-default">Сохранить</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
        </div>
    }

<!--Permission group-->
<script type="text/javascript">
    function OnSuccessPermission(data) {
        //alert('Ok');
        var jsfullName = data.fullName == "" ? "" : '<b>' + data.fullName + '</b>';
        var jsstart = data.start == "" ? "" : '<p><b>Дата начала полномочий: </b>' + data.start + '.</p>';
        var jsfinish = data.finish == "" ? "." : ' со сроком полномочий вплоть до ' + data.finish + '.';
        var jsworkOfPlace = data.workOfPlace == "" ? "" : '<p><b>Место работы: </b>' + data.workOfPlace + '.</p>';
        var jspost = data.post == "" ? "" : '<p><b>Должность: </b>' + data.post + '.</p>';
        var jsaddress = data.address == "" ? "" : '<p><b>Место проживания: </b>' + data.address + '.</p>';
        var jsphone = data.phone == "" ? "" : '<p><b>Телефон: </b>' + data.phone + '.</p>';
        var jsfax = data.fax == "" ? "" : '<p><b>Факс: </b>' + data.fax + '.</p>';
        var jspassport = data.passport == "" ? "" : '<p><b>Паспортные данные: </b>' + data.passport + '.</p>'
        var jscollapseinformation = jsworkOfPlace + jspost + jsaddress + jspassport + jsphone + jsfax + jsstart;

        var PermissionMackupForInsert = $('<div class="panel panel-default" id="panelCustomBrockerPermission' + 10000001 + data.id + '">' +
            '<div class="panel-heading" role = "tab" id = "headingCustomBrockerPermission' + 10000001 + data.id + '" > ' +
            '<a type="button" class="close" id="deleteButtonCustomBrockerPermission' + 10000001 + data.id + '"data-ajax="true" data-ajax-mode="replace" data-ajax-update="#CustomBrockerPermissionDeleteAccept" data-ajax-success="$(\'#CustomBrockerPermissionDeleteModal\').modal(\'show\')" href="/permissions/PartialDelete/' + data.id + '"><span aria-hidden="true">&times;</span></a>' +
            '<a type="button" class="close" id="editButtonCustomBrockerPermission' + 10000001 + data.id + '"data-ajax="true" data-ajax-mode="replace" data-ajax-update="#CustomBrockerPermissionEditAccept" data-ajax-success="$(\'#CustomBrockerPermissionEditModal\').modal(\'show\')" href="/permissions/PartialEdit/' + data.id + '"><span aria-hidden="true" class="glyphicon glyphicon-pencil"></span></a>' +
            '<h4 class="panel-title">' +
            '<a role="button" data-toggle="collapse" data-parent="#accordionCustomBrockerPermission" href="#collapseCustomBrockerPermission' + 10000001 + data.id + '" aria-expanded="false" aria-controls="collapseCustomBrockerPermission' + 10000001 + data.id + '">' +
            'Уполномоченный представитель: ' + jsfullName + jsfinish +
            '<input type="hidden" name="permission[' + data.id + '].PERMISSIONID" value="' +
            + data.id + '"><input type="hidden" value="' + data.id + '"name="permission.Index">' +
            '</a >' +
            '</h4>' +
            '</div >' +
            '<div id = "collapseCustomBrockerPermission' + 10000001 + data.id + '" class= "panel-collapse collapse" role = "tabpanel" aria-labelledby="headingCustomBrockerPermission' + data.id + 10000001 + '" >' +
            '<div class="panel-body">' +
            jscollapseinformation +
            '</div>' +
            '</div >' +
            '</div >');
        $('#anchorForCustomBrockerPermission').before(PermissionMackupForInsert);
        $('#permissionModal').modal('hide');
        CollapsePanel('collapseCustomBrockerPermission' + 10000001 + data.id);

        function CollapsePanel(panel) {
            var collapsePanel = document.getElementById(panel);
            collapsePanel.collapse('hide');
        }
    }</script>

<!--Custom brocker modal.-->
<div class="modal fade" id="brockerModal" tabindex="-1" role="dialog">
    @using (Ajax.BeginForm("Search", "custombrockers", new AjaxOptions { UpdateTargetId = "brockerresults" }))
    {
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" id="buttonBrockerModalClose" data-dismiss="modal" onclick="CloseOnlyInnerModal()"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Выбор таможенного представителя</h4>
                </div>
                <div class="modal-body">
                    <div>

                        <div class="input-group" style="max-width: 380px;">
                            <input type="text" class="form-control" name="lastName" placeholder="Введите часть фамилии..." />
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default">Поиск</button>
                                @Ajax.ActionLink("Создать", "PartialCreate", "custombrockers", null,
                                new AjaxOptions { UpdateTargetId = "brockerresults" }, new { @class = "btn btn-default" } )
                            </div>
                        </div>


                        <div id="brockerresults"></div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    }
</div>
<script>
    function CloseOnlyInnerModal() {
        $('#buttonBrockerModalClose').prop('data-dismiss').remove();
        $('#brockerModal').modal('hide');
        ;

    }
</script>

<!--Modal dialog for device deleting-->
<div class="modal fade" id="CustomBrockerPermissionDeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-notify modal-success" role="document">
        <!--Content-->
        <div class="modal-content">
            <!--Header-->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Удаление разрешения</h4>
            </div>
            <div id="CustomBrockerPermissionDeleteAccept"></div>
        </div>
        <!--/.Content-->
    </div>
</div>
<!--Modal dialog for device editing-->
<div class="modal fade" id="CustomBrockerPermissionEditModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-notify modal-warning" role="document">
        <!--Content-->
        <div class="modal-content">
            <!--Header-->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Изменение сведений об разрешении</h4>
            </div>
            <div id="CustomBrockerPermissionEditAccept"></div>
        </div>
        <!--/.Content-->
    </div>
</div>
<script>
    function CustomBrockerPermissionButtonCloseHide() {
        $('#CustomBrockerPermissionModalCloseButton').hide();

    }
    function CustomBrockerPermissionButtonCloseShow() {
        $('#CustomBrockerPermissionModalCloseButton').show();

    }
</script>